version: '3'

services:

  oxid6_apache:
    build: container/apache_php7/.
    hostname: ${DOMAIN}
    restart: always
    depends_on:
      - oxid6_mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro #Get the timezone of the host.
      - ${PWD}/data/www/:/var/www/html/:cached
    environment:
      DOMAIN: ${DOMAIN}
      APACHE_PORT: ${APACHE_PORT}
      OXID_VERSION: ${OXID_VERSION}
      OXID_DEMODATA: ${OXID_DEMODATA}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${APACHE_PORT}:80
    links:
      - oxid6_mailhog:mail.server
      
  oxid6_mysql:
    image: mysql:5.7
    hostname: mysql.${DOMAIN}
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro #Get the timezone of the host
      - ${PWD}/data/mysql/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  oxid6_memcache:
    image: memcached
    restart: always
    mem_limit: 128m
    memswap_limit: 128m
    mem_reservation: 96m
  
  oxid6_mailhog:
    hostname: mailhog.${DOMAIN}
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT}:8025
    volumes:
      - /etc/localtime:/etc/localtime:ro #Get the timezone of the host

  oxid6_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: oxid6_mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro #Get the timezone of the host
